config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :products
  resources :cartegories
  get 'store/index'

  root to: 'store#index'
  get 'admin' => 'admin#index'
  get 'register' => 'users#new'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cartegory.rb
class Cartegory < ApplicationRecord
	validates :name, :presence => true, :uniqueness => true
  	has_many :childrens, class_name: 'Cartegory', foreign_key: :parent_id
  	belongs_to :parent,  class_name: 'Cartegory', primary_key: :id
  	has_many :products, foreign_key: :parent_id, inverse_of: :cartegory
 private
 	def init
 		self.parent_id = 0 unless self.parent_id
 	end
end

app/controllers/cartegories_controller.rb
class CartegoriesController < ApplicationController
  before_action :set_cartegory, only: [:show, :edit, :update, :destroy]
  before_action :authorize

  # GET /cartegories
  # GET /cartegories.json
  def index
    @cartegories = Cartegory.all
    @page_title = "ProductManager|Cartegories"
  end

  # GET /cartegories/1
  # GET /cartegories/1.json
  def show
    @page_title = "ProductManager|Cartegories Details"
  end

  # GET /cartegories/new
  def new
    @cartegory = Cartegory.new
    @page_title = "ProductManager|New Cartegory"

  end

  # GET /cartegories/1/edit
  def edit
   @page_title = "ProductManager|Edit Cartegory"
  end

  # POST /cartegories
  # POST /cartegories.json
  def create
    @cartegory = Cartegory.new(cartegory_params)

    respond_to do |format|
      if @cartegory.save
        format.html { redirect_to cartegories_url, notice: 'Cartegory was successfully created.' }
        format.json { render :show, status: :created, location: @cartegory }
      else
        format.html { render :new }
        format.json { render json: @cartegory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cartegories/1
  # PATCH/PUT /cartegories/1.json
  def update
    respond_to do |format|
      if @cartegory.update(cartegory_params)
        format.html { redirect_to cartegories_url, notice: 'Cartegory was successfully updated.' }
        format.json { render :show, status: :ok, location: @cartegory }
      else
        format.html { render :edit }
        format.json { render json: @cartegory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cartegories/1
  # DELETE /cartegories/1.json
  def destroy
    @cartegory.destroy
    respond_to do |format|
      format.html { redirect_to cartegories_url, notice: 'Cartegory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cartegory
      @cartegory = Cartegory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cartegory_params
      params.require(:cartegory).permit(:name, :parent_id)
    end
end

app/helpers/cartegories_helper.rb
module CartegoriesHelper
end

app/views/cartegories/_cartegory.html.erb
<li class="dropdown-submenu">
    <a href="#"><%=cartegory.name%></a>
    <%if cartegory.childrens.present?%>
        <ul class="dropdown-item">
        	<%cartegory.childrens.each do |cart|%>
          		<li><a href="#"><%=cart.name%></a></li>
          	<%end%>
        </ul>
     <%end%>
      <li class="divider" role="separator"></li>
</li>		

app/views/cartegories/_form.html.erb
<div class = "product_form">
<%= form_with(model: @cartegory, local: true) do |form| %>
  <% if @cartegory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cartegory.errors.count, "error") %> prohibited this cartegory from being saved:</h2>

      <ul>
      <% @cartegory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>  
  <legend>Enter Cartegories Details </legend>
  <div class="field">
    <%= form.label :name, 'Name' %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :parent_id, 'Cartegory'%>
    <%= form.select :parent_id, root_cartegories.collect{|c| [c.name, c.id]}, :prompt => 'Select a parent cartegory...' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  </fieldset>
<% end %>
</div>

app/views/cartegories/edit.html.erb
<title>Product Manager|Edit Cartegory</title>
<h1>Editing Cartegory</h1>

<%= render 'form'%>

<%= link_to 'Show', @cartegory %> |
<%= link_to 'Back', cartegories_path %>

app/views/cartegories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cartegories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cartegories.each do |cartegory| %>
      <tr>
        <td><%= cartegory.name %></td>
        <td>
            <%= cartegory.parent.try(:name)%>        
        </td>
        <% if can? :show, cartegory %>
        <td><%= link_to 'Show', cartegory %></td>
        <%end%>
        <% if can? :update, cartegory %>
        <td><%= link_to 'Edit', edit_cartegory_path(cartegory) %></td>
        <%end%>
        <% if can? :destroy, cartegory %>
        <td><%= link_to 'Destroy', cartegory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cartegory', new_cartegory_path %>

app/views/cartegories/new.html.erb
<title>Product Manager|New Cartegory</title>

<h1>New Cartegory</h1>

<%= render 'form'%>

<%= link_to 'Back', cartegories_path %>

app/views/cartegories/show.html.erb
<title>Product Manager|Cartegory List</title>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cartegory.name %>
</p>

<p>
  <strong>Parent:</strong>
   <%= @cartegory.parent.try(:name)%>  
</p>

<p><strong>Product</strong><p>
<br>
<% if @cartegory.products.present?%>
<table>
 <tbody>
    <% @cartegory.products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <% if can? :show, product %>
        <td><%= link_to 'Show', product %></td>
        <% end %>
        <% if can? :update, product %>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <% end %>
        <% if can? :destroy, product %>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%end%>
<%= link_to 'Edit', edit_cartegory_path(@cartegory) %> |
<%= link_to 'Back', cartegories_path %>