config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :products
  resources :cartegories
  get 'store/index'

  root to: 'store#index'
  get 'admin' => 'admin#index'
  get 'register' => 'users#new'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title || "Product Manager" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
  </head>

  <body>
      <nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href=<%=root_path%>>Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href=<%=products_path%>>Products<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href=<%=cartegories_path%>>Cartegories<span class="sr-only">(current)</span></a>
            </li>
          </ul>
        </div>
        <div>
          <%= button_to 'Logout', '/logout', :method => :delete , :class => "btn btn-outline-success my-2 my-sm-0" %> 
        </div>
      </nav>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title || "Product Manager" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
  </head>

  <body>
      <nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Product Manager</a>        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href=<%=root_path%>>Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href=<%=products_url%>>Products</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Cartegories
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%=root_cartegories.each do |cartegory|%>
                   <li class="dropdown-submenu">
                      <a href="#"><%=cartegory.name%></a>
                        <%if cartegory.childrens.present?%>
                            <ul class="dropdown-item">
                              <%cartegory.childrens.each do |cart|%>
                                <li><%= link_to cart.name, cart%></li>
                              <%end%>
                            </ul>
                        <%end%>
                      <li class="divider" role="separator"></li>
                    </li> 
                <%end%>
               </ul>
            </li>
          </ul>
        </div>
        <%= form_tag(products_path, :method => "get", class: "form-inline my-2 my-lg-0") do %>
          <%= text_field_tag :search, params[:search], placeholder: "search here",
            class: "form-control mr-sm-2" %>
          <%= submit_tag "Search", class: 'btn btn-outline-success my-2 my-sm-0' %>
        <%end%>
        <div>
          <%= button_to 'Logout', '/logout', :method => :delete , :class => "btn btn-outline-success my-2 my-sm-0" %> 
        </div>
      </nav>
    <%= yield %>
  </body>
</html>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title || "Product Manager" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
  </head>

  <body>
      <nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Product Manager</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </nav>
    <%= yield %>
  </body>
</html>